# Generated by Django 5.1.7 on 2025-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_alter_order_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="promotions/%Y/%m/%d", verbose_name="Изображение"
                    ),
                ),
                (
                    "discount",
                    models.CharField(blank=True, max_length=50, verbose_name="Скидка"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная"),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, to="shopapp.product", verbose_name="Товары по акции"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-start_date"],
            },
        ),
    ]
