# Generated by Django 5.1.7 on 2025-06-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_remove_product_tags_order_delivery_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
